### ISSUE TITLE
Community Management

### ISSUE THREAD

**Issue by mttrbrts** [accordproject/technical-steering-committee#53]
# Objective 🗣
A project to grow engagement with and within the Accord Project community.

# Discussion
We should better understand our community. Who is new? What are the common challenges? What are the barriers to engagement and adoption?

This is a deliberately broad topic with scope for multiple members to share the work over several quarters. It could involve elements of Partnership, Outreach, Analysis, Social Media management, Product Management etc.

# Tasks
- [ ] We should properly engage with https://orbit.love/ (we have an existing stale account).
- [ ] Build original content to communicate our value proposition, and point-of-view (related to (#49))
- [ ] Refresh our social media presence (#51)
- [ ] Make proactive contact with high-reach community members
- [ ] Review "first-touch" experience
- [ ] Chores and maintenance

**Comment by mttrbrts** [comment]
Adopted orbit and integrated with key systems. Basic monitoring in place will allow us to track our growth initiatives.
